FROM node:alpine

WORKDIR '/app'

COPY ./package.json yarn.lock ./
COPY ./lerna.json ./

RUN yarn install --frozen-lockfile

COPY ./frontend ./frontend

RUN npx lerna bootstrap

CMD ["yarn", "run", "start:frontend"]