version: '3'
services:
  mongo:
    image: mongo:latest
    environment: 
      - MONGO_INITDB_DATABASE=lyricaldb
      - MONGO_INITDB_USERNAME=ccrespo
      - MONGO_INITDB_PASSWORD=secret
    volumes:
      - ./server/config/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'
    depends_on:
      - api
      - client
  api:
    build: 
      context: .
      dockerfile: ./server/Dockerfile.dev
    volumes:
      - /app/server/node_modules
      - ./server:/app/server
      - ./tsconfig.json:/app/tsconfig.json
  client:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    volumes:
      - /app/frontend/node_modules
      - ./frontend:/app/frontend
      - ./tsconfig.json:/app/tsconfig.json