FROM node:alpine as builder

RUN npm i lerna -g --loglevel notice

WORKDIR '/app'

COPY package.json yarn.lock lerna.json ./

RUN yarn install --pure-lockfile

COPY frontend/ ./frontend
COPY server/ ./server

RUN npx lerna bootstrap

CMD ["npm", "run", "start:dev"]
