FROM node:alpine as builder

RUN npm i lerna -g --loglevel notice

WORKDIR '/app'

COPY jest.config.json tsconfig.json ./
COPY package.json yarn.lock lerna.json ./

RUN yarn install --frozen-lockfile

COPY frontend/ ./frontend
COPY server/ ./server

RUN yarn bootstrap

CMD ["npm", "run", "start:dev"]
