FROM node:alpine

RUN npm install -g nodemon

WORKDIR '/app'

COPY ./package.json yarn.lock ./
COPY ./lerna.json ./

RUN yarn install --frozen-lockfile

COPY ./server ./server

RUN npx lerna bootstrap

CMD ["yarn", "run", "start:dev:server"]